import { useState } from "react";
import { createPortal } from "react-dom";
import { PaperSheet } from "./PaperSheet";
import { StepGuidance } from "./StepGuidance";
import { usePaperSheetAutosave } from "../../hooks/usePaperSheetAutosave";
import { usePaperSheetOpen } from "../../hooks/usePaperSheetOpen";
import { usePaperSheetFocus } from "../../hooks/usePaperSheetFocus";
import type { HunterCard } from "@/types";

const STEPS = [1, 2, 3, 4, 5] as const;

/** The paper sheet as a full-screen popup: dark desk background, the original
 * sheet toolbar (steps toggle, clear, PDF export) and autosave to Firestore.
 * `readOnly` is for looking at someone else's hunter (party view); `create`
 * marks the one surface allowed to CREATE the doc (a brand-new draft). */
export function PaperSheetModal({
  card,
  onClose,
  readOnly = false,
  create = false,
}: {
  card: HunterCard;
  onClose: () => void;
  readOnly?: boolean;
  create?: boolean;
}) {
  const { data, setField, saveMsg, clear } = usePaperSheetAutosave(card, { readOnly, create });
  const [showSteps, setShowSteps] = useState(true);
  // Which creation step (1–5) is spotlighted on the sheet; null = none.
  const [activeStep, setActiveStep] = useState<number | null>(null);
  usePaperSheetOpen();
  const doneRef = usePaperSheetFocus(onClose);

  return createPortal(
    <div className="papersheet-modal" role="dialog" aria-modal="true" aria-label="Character sheet">
      <div className="papersheet-toolbar">
        <button type="button" className="ghost" ref={doneRef} onClick={onClose}>← Done</button>
        <h1>CATACOMBS &amp; STARSPAWNS · CHARACTER SHEET</h1>
        <span className="savemsg">{readOnly ? "Read-only" : saveMsg}</span>
        <div className="stepsel" role="group" aria-label="Highlight a character-creation step">
          <span className="steplbl">Step</span>
          {STEPS.map((n) => (
            <button
              key={n}
              type="button"
              className={activeStep === n ? "stepbtn active" : "stepbtn"}
              aria-pressed={activeStep === n}
              title={`Highlight everything you fill in during step ${n}`}
              onClick={() => setActiveStep((s) => (s === n ? null : n))}
            >
              {n}
            </button>
          ))}
        </div>
        {activeStep != null && <StepGuidance step={activeStep} />}
        <label>
          <input type="checkbox" checked={showSteps} onChange={(e) => setShowSteps(e.target.checked)} />
          Show step numbers
        </label>
        {!readOnly && (
          <button type="button" className="ghost" onClick={clear}>Clear sheet</button>
        )}
        <button type="button" className="ghost" onClick={() => window.print()}>Print</button>
        {/* Pre-made blank sheet, generated by scripts/generate-sheet-pdf.mjs
          * and served (CDN-cached) from Hosting — matches the steps toggle. */}
        <a href={showSteps ? "/sheet/character-sheet-numbered.pdf" : "/sheet/character-sheet.pdf"} download>
          Blank PDF
        </a>
      </div>
      <PaperSheet data={data} setField={setField} readOnly={readOnly} hideSteps={!showSteps} activeStep={activeStep} />
    </div>,
    document.body,
  );
}
