#!/usr/bin/env python3
"""Generate src/data/backgrounds.ts + feats.ts from resources/master.json.

master.json is the consolidated source of truth for game content. This emits the
two creation-time data files the app needs (the Backgrounds chapter table and the
Feats chapter prose). Re-run after a content refresh:  python gen_from_master.py
"""
import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
MASTER = json.load(open(os.path.join(REPO, "resources", "master.json"), encoding="utf-8"))
SRC = os.path.join(REPO, "src", "data")

ABIL = {"strength": "str", "dexterity": "dex", "constitution": "con",
        "intelligence": "int", "wisdom": "wis", "charisma": "cha"}
SMALL = {"of", "the", "and", "a", "an", "to", "for"}


def js(s):
    return json.dumps(s, ensure_ascii=False)


def kebab(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def title(name):
    parts = name.strip().lower().split()
    out = []
    for i, w in enumerate(parts):
        # keep hyphenated words capitalised on both sides: two-weapon -> Two-Weapon
        seg = "-".join(p if (i > 0 and p in SMALL) else p.capitalize() for p in w.split("-"))
        out.append(seg)
    return " ".join(out)


def chapter(name):
    return next(c for c in MASTER["handbook"]["chapters"] if c["title"] == name)


# ---------------- Backgrounds ----------------
bg_sec = chapter("Backgrounds")["sections"][0]
part1, part2 = {}, {}
for t in bg_sec["tables"]:
    if "Ability Scores" in t["columns"]:
        for r in t["rows"]:
            part1[r[0]] = {"text": r[1], "abilities": r[2]}
    if "Feat" in t["columns"]:
        for r in t["rows"]:
            part2[r[0]] = {"feat": r[1], "skills": r[2], "tool": r[3], "equip": r[4]}


def split_list(cell):
    cell = (cell or "").strip()
    if cell in ("", "—", "—"):
        return []
    cell = cell.replace(" and ", ", ")
    return [x.strip() for x in cell.split(",") if x.strip()]


def one(cell):
    cell = (cell or "").strip()
    return None if cell in ("", "—", "—") else cell


def feat_cell(cell):
    cell = (cell or "").strip()
    if not cell or "not legible" in cell.lower() or cell in ("—", "—"):
        return None
    return cell


backgrounds = []
for name in part2:  # part2 is the canonical 14-row list
    p1 = part1.get(name, {})
    abilities = [ABIL[a.strip().lower()] for a in (p1.get("abilities") or "").split(",") if a.strip().lower() in ABIL]
    p2 = part2[name]
    backgrounds.append({
        "id": kebab(name),
        "name": name,
        "text": (p1.get("text") or "").strip(),
        "abilityScores": abilities,
        "feat": feat_cell(p2["feat"]),
        "skills": split_list(p2["skills"]),
        "tool": one(p2["tool"]),
        "equipment": split_list(p2["equip"]),
    })

bg_lines = [
    "// GENERATED by resources/extracted/gen_from_master.py — do not edit by hand.",
    "// Source: resources/master.json (Players Handbook, Chapter 3 — Backgrounds).",
    'import type { Background } from "@/types";',
    "",
    "export const BACKGROUNDS: Background[] = [",
]
for b in backgrounds:
    bg_lines.append("  {")
    bg_lines.append("    id: %s," % js(b["id"]))
    bg_lines.append("    name: %s," % js(b["name"]))
    bg_lines.append("    text: %s," % js(b["text"]))
    bg_lines.append("    abilityScores: [%s]," % ", ".join(js(a) for a in b["abilityScores"]))
    bg_lines.append("    feat: %s," % (js(b["feat"]) if b["feat"] else "null"))
    bg_lines.append("    skills: [%s]," % ", ".join(js(s) for s in b["skills"]))
    bg_lines.append("    tool: %s," % (js(b["tool"]) if b["tool"] else "null"))
    bg_lines.append("    equipment: [%s]," % ", ".join(js(e) for e in b["equipment"]))
    bg_lines.append("  },")
bg_lines.append("];")
bg_lines.append("")
open(os.path.join(SRC, "backgrounds.ts"), "w", encoding="utf-8", newline="\n").write("\n".join(bg_lines))
print("wrote backgrounds.ts (%d backgrounds)" % len(backgrounds))

# ---------------- Feats ----------------
CAT = {"Origin Feats": "Origin", "General Feats": "General",
       "Fighting Style Feats": "Fighting Style", "Epic Boon Feats": "Epic Boon"}
feats = []
for sec in chapter("Feats")["sections"]:
    cat = CAT.get(sec["heading"])
    if not cat:
        continue
    chunks = [c.strip() for c in sec["text"].split("\n\n") if c.strip()]
    for ch in chunks[1:]:  # [0] is the "These feats are in the X category." intro
        m = re.match(r"^([A-Z][A-Z0-9 \-'’]+?)\s*(\(Prerequisite:[^)]*\))?\.\s+(.*)$", ch, re.S)
        if not m:
            continue
        raw_name, prereq, text = m.group(1).strip(), m.group(2), m.group(3).strip()
        pre = None
        if prereq:
            pre = prereq[1:-1].split(":", 1)[1].strip()  # inside parens, after "Prerequisite:"
        feats.append({"id": kebab(raw_name), "name": title(raw_name), "category": cat,
                      "prerequisite": pre, "text": re.sub(r"\s+", " ", text)})

ft_lines = [
    "// GENERATED by resources/extracted/gen_from_master.py — do not edit by hand.",
    "// Source: resources/master.json (Players Handbook, Chapter 4 — Feats).",
    'import type { Feat } from "@/types";',
    "",
    "export const FEATS: Feat[] = [",
]
for f in feats:
    ft_lines.append("  {")
    ft_lines.append("    id: %s," % js(f["id"]))
    ft_lines.append("    name: %s," % js(f["name"]))
    ft_lines.append("    category: %s," % js(f["category"]))
    ft_lines.append("    prerequisite: %s," % (js(f["prerequisite"]) if f["prerequisite"] else "null"))
    ft_lines.append("    text: %s," % js(f["text"]))
    ft_lines.append("  },")
ft_lines.append("];")
ft_lines.append("")
open(os.path.join(SRC, "feats.ts"), "w", encoding="utf-8", newline="\n").write("\n".join(ft_lines))
print("wrote feats.ts (%d feats: %s)" % (
    len(feats), ", ".join("%s=%d" % (c, sum(1 for f in feats if f["category"] == c))
                          for c in ["Origin", "General", "Fighting Style", "Epic Boon"])))
